### ISSUE TITLE
Summary Table: Conditional Body Background Colour - Returns to White after hover a table cell.

### ISSUE THREAD

**Issue by wjsmith87** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#335]
I have conditional format for the 'Body Background Colour' for the summary table. After hovering a cell the background colour return to white instead of the colour specified. 

Data in image is dummy data:
![image](https://github.com/user-attachments/assets/f319bea0-4d87-420c-8955-2c280fddc53a)

**Comment by andrjohns** [comment]
Thanks for reporting! Should now be fixed in the development version

**Comment by wjsmith87** [comment]
Hi, I have just updated to the latest dev version and I'm still getting the same issue.

**Comment by wjsmith87** [comment]
Sorry, Actually this looks like the fix worked. Reopened the dashboard and noticed it does work.
